encryptionsalt: v1:c+R1TgvyWag=:v1:GjeOoWIbcj0TUr0M:DpC5yDhjTOywSrexH4+PIcsxlZw2tw==
config:
  ephemeral-github-runner:bootDiskSizeInGB: "100"
  ephemeral-github-runner:bootDiskType: pd-balanced
  ephemeral-github-runner:env: dev
  ephemeral-github-runner:ghRunnerName: orville
  ephemeral-github-runner:ghToken: test
  ephemeral-github-runner:machineImage: projects/ml-images/global/images/c0-deeplearning-common-cu110-v20211022-debian-10
  ephemeral-github-runner:machineType: e2-micro
  ephemeral-github-runner:repo: rtrack
  ephemeral-github-runner:repoOwner: pavlovic-ivan
  ephemeral-github-runner:runnersCount: "1"
  ephemeral-github-runner:serviceAccountEmail: 121448003753-compute@developer.gserviceaccount.com
  ephemeral-github-runner:serviceAccountScopes: default
  ephemeral-github-runner:zone: europe-west4-a
